### ISSUE TITLE
이미지가 깨지는데 확인 부탁드립니다.

### ISSUE THREAD

**Issue by jhk0530** [pg-vscode-extn-kr/pg-vscode-extn-kr.github.io#13]
working with extension - publishing-extension에서

https://github.com/pg-vscode-extn-kr/pg-vscode-extn-kr.github.io/blob/master/api/working-with-extensions/publishing-extension.md

personal access token쪽 이미지 링크 전부 깨짐

**Comment by jeonhyun97** [comment]
그거 이미지 다운로드가 애초에 잘못되어서 전 부분이 다 그럽니다. 
시간날때 고쳐야 하는데 시간이 잘 안나네요 ㅠㅠ
천천히 고치겠습니다.
