### ISSUE TITLE
customize 번역 제안

### ISSUE THREAD

**Issue by jhk0530** [pg-vscode-extn-kr/pg-vscode-extn-kr.github.io#15]
사용자화 보단 커스터마이즈가 나을 것 같은데 검토  바랍니다.

can be customized and enhanced through the Extension API.

* 익스텐션 API를 통해 사용자화하고 발전시킬 수 있습니다.
* 익스텐션 API를 통해 커스터마이즈하고 발전시킬 수 있습니다.

**Comment by jeonhyun97** [comment]
괜찮은 것 같습니다.
리드미에도 추가해주세요.

**Comment by jhk0530** [comment]
organization owner가 아니라 member라서 수정 권한이 없어요...

**Comment by jeonhyun97** [comment]
바꾸시고 풀리퀘 해주시면 됩니다 
천천히 수정해나가면 될듯요

**Comment by jhk0530** [comment]
![image](https://user-images.githubusercontent.com/6457691/71940733-c54d8b80-31fa-11ea-9e46-34b0fd076a37.png)
