### ISSUE TITLE
rule 추가 

### ISSUE THREAD

**Issue by jhk0530** [pg-vscode-extn-kr/pg-vscode-extn-kr.github.io#5]
## Additional rules for translation 에 추가

예시 code, command, parameter, variable, 내부 comment 는 번역 안함  
ex) `npm install -g yo generator-code`
ex) `vscode.window.showInformationMessage`

## Terminology Translation에 추가

JavaScript (Project) -> JavaScript (Project)
TypeScript (Project) -> TypeScript (Project)
generator -> generator  # 커맨드 이름 같아서 그냥 씀
breakpoint -> breakpoint # 중지점이랑 breakpoint 고민하고 결정
API -> API

**Comment by jeonhyun97** [comment]
javascript는 자바스크립트, typescript는 타입스크립트로 번역하면 좋을 듯

**Comment by jhk0530** [comment]
그럼 project도 프로젝트로 바꿔야겠구만
