### ISSUE TITLE
branch를 브런치가 아닌 브랜치로 번역 제안합니다.

### ISSUE THREAD

**Issue by SimYunSup** [pg-vscode-extn-kr/pg-vscode-extn-kr.github.io#54]
현재 `branch`는 브런치로 번역되어 있습니다. 그런데 국립국어원에서 [한국어 어문 규범](http://kornorms.korean.go.kr/example/exampleList.do?regltn_code=0003)을 찾아 보면 `branch`를 브랜치라고 번역한 용례가 적혀있으며 구글에 `branch 브런치라고 검색해봐도 브랜치라고 번역된 결과가 더욱 많습니다.

그러므로 branch를 브런치가 아닌 브랜치로 번역할 것을 제안합니다.

**Comment by jhk0530** [comment]
readme에 추가 함
