### ISSUE TITLE
Get started-당신의 첫번째 익스텐션에서 비디오 재생이 되지 않음

### ISSUE THREAD

**Issue by SimYunSup** [pg-vscode-extn-kr/pg-vscode-extn-kr.github.io#55]
**Describe the bug**
현재 비디오가 assets 파일에 없어서 생긴 오류로 보입니다.

**Expected behavior**

비디오 재생이 스크롤 될 시에 재생되어야 합니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/47362439/73608270-6108c680-4604-11ea-8683-86bee36b0149.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser firefox
 - Version 72.0.2

**Comment by jhk0530** [comment]
수정 완료, 확인 후에 Issue Close 바랍니다.

**Comment by SimYunSup** [comment]
@jhk0530 style="width:100%" 태그가 필요해 보입니다. 수정 후에 PR 올리겠습니다.
