### ISSUE TITLE
번역 제안: Publish를 게시하다/게시로 번역

### ISSUE THREAD

**Issue by SimYunSup** [pg-vscode-extn-kr/pg-vscode-extn-kr.github.io#57]
publishing을 그대로 퍼블리시/퍼블리싱으로 번역하는 것은 어색해보입니다. 같은 마이크로소프트 문서에서는 [publish](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension?view=vs-2019)를 [게시](https://docs.microsoft.com/ko-kr/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension?view=vs-2019)로 번역 하였으니 이를 따라가는 것이 좋아보입니다.

**Comment by jhk0530** [comment]
OK, Readme.md 수정해서 PR 걸어주세요. 
이후 issue close 하겠습니다.
