### ISSUE TITLE
CI Failure

### ISSUE THREAD

**Issue by jhk0530** [pg-vscode-extn-kr/pg-vscode-extn-kr.github.io#65]
![image](https://user-images.githubusercontent.com/6457691/73623027-cf8a6a80-467e-11ea-9da9-dc7889e2bebf.png)

_sass/custom/custom.scss 에 

`img`, `video` 속성 추가 후 발생

**Comment by SimYunSup** [comment]
convention을 지키지 않아 생긴 오류같습니다.

변경후 PR하겠습니다.
